openapi: 3.0.0
info:
  title: Express API for Foodmaze
  description: This is a simple API
  version: 1.0.0
servers:
- url: http://localhost:8080
  description: Local machine
- url: https://restaurant-express-api.onrender.com
  description: Render
security:
- application:
  - read
  - write
paths:
  /foods:
    post:
      summary: Món ăn
      operationId: foods
      tags:
        - Food
      description: Món ăn
      parameters:
        - $ref: '#/components/parameters/requestId'
        - in: header
          name: x-lang
          description: Ngôn ngữ
          required: true
          schema:
            type: string
            enum: 
            - vi
            - en
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                instrument:
                  description: Mã CK
                  type: string
                  example: ACB
                qty:
                  description: Khối luợng
                  type: number
                  example: 1
                side:
                  description: Mua bán
                  type: string
                  enum:
                    - buy
                    - sell
                  example: buy
                type:
                  description: Loại lệnh
                  type: string
                  enum:
                    - LO
                    - ATO
                    - ATC
                    - MP
                    - MTL
                    - MOK
                    - MAK
                  example: LO
                limitPrice:
                  description: Giá
                  type: number
                  example: 7000
                stopPrice:
                  description: Giá stop (nếu có).
                  type: number
                durationType:
                  description: Loại thời gian (nếu có).
                  type: string
                  example: gtt
                durationDateTime:
                  description: Thời hạn UNIX timestamp (nếu có dùng durationType).
                  type: number
                  example: 1548406235
                stopLoss:
                  description: Giá cắt lỗ (nếu có).
                  type: number
                takeProfit:
                  description: Giá chốt lời (nếu có).
                  type: number
                digitalSignature:
                  description: CKS (nếu có).
                  type: string
                  example: 954345868
                timetype:
                  description: loại lệnh (T -> lệnh thuườg, G -> lệnh dk)
                  type: string
                  enum:
                    - T
                    - G
                splitval:
                  description: Khối lượng chia
                  type: number
                effdate: 
                  description: Ngày hiệu lực
                  type: string
                expdate:
                  description: Ngày hết hiệu lực
                  type: string
              required:
                - instrument
                - qty
                - side
                - type
                - timetype
      responses:
        200:
          description: PostOrderResponse
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/Status'
      security:
      - accessCode: []
components:
  schemas:
    Status:
      type: string
      enum:
      - ok
      - error
  parameters:
    requestId:
      name: requestId
      in: query
      description: Unique identifier for a request.
      required: false
      style: form
      explode: true
      schema:
        type: string
      example: 23425678343
  securitySchemes:
    accessCode:
      type: oauth2
      flows:
        password:
          tokenUrl: 'https://restaurant-express-api.onrender.com/login'
          scopes:
            account-read: account-read
            account-write: account-write